<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2">
    <title>403 Forbidden</title>
</head>
<style>
    @font-face
    {
        font-family: 'Oswald';
        font-style: normal;
        font-weight: 300;
        font-display: swap;
        src: url(/storage/assets/font/Oswald-Light.woff2) format('woff2');
    }
    
    body
    {
        background: radial-gradient(#712B75 5%, #16213E 95%);
    }

    #container
    {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 95vh;
    }

    .header
    {
        color: #eeeeee;
        font-family: 'Oswald', sans-serif;
        font-size: 24px;
        font-weight: bold;
        text-shadow: -1px -1px 1px #2E0249, 1px -1px 1px #2E0249, -1px 1px 1px #2E0249, 1px 1px 1px #2E0249;
    }

    .dim-vertical
    {
        background: #eeeeee;
        border: 1.9px solid #eeeeee;
        height: 10px;
        margin: 0px 12px 0px 12px;
    }
</style>
<body>
    <div id="container">
        <div class="header" aria-description="the link address or destination page was not found">
            <?= $httpResponseCode ?><span class="dim-vertical"></span><span id="responseCodeText"></span>
        </div>
    </div>
    <script>
        const httpResponseCode =
        {
            '200': 'OK',
            '201': 'Created',
            '202': 'Accepted',
            '203': 'Non-Authoritative Information',
            '204': 'No Content',
            '205': 'Reset Content',
            '206': 'Partial Content',
            '300': 'Multiple Choices',
            '301': 'Moved Permanently',
            '302': 'Found',
            '303': 'See Other',
            '304': 'Not Modified',
            '305': 'Use Proxy',
            '306': 'Unused',
            '307': 'Temporary Redirect',
            '400': 'Bad Request',
            '401': 'Unauthorized',
            '402': 'Payment Required',
            '403': 'Forbidden',
            '404': 'Not Found',
            '405': 'Method Not Allowed',
            '406': 'Not Acceptable',
            '407': 'Proxy Authentication Required',
            '408': 'Request Timeout',
            '409': 'Conflict',
            '410': 'Gone',
            '411': 'Length Required',
            '412': 'Precondition Required',
            '413': 'Request Entry Too Large',
            '414': 'Request-URI Too Long',
            '415': 'Unsupported Media Type',
            '416': 'Requested Range Not Satisfiable',
            '417': 'Expectation Failed',
            '418': 'I\'m a teapot',
            '429': 'Too Many Requests',
            '500': 'Internal Server Error',
            '501': 'Not Implemented',
            '502': 'Bad Gateway',
            '503': 'Service Unavailable',
            '504': 'Gateway Timeout',
            '505': 'HTTP Version Not Supported',
        };

        document.getElementById("responseCodeText").innerHTML = httpResponseCode['<?= $httpResponseCode ?>'];
        document.querySelector('title').textContent = `<?= $httpResponseCode ?> ${httpResponseCode['<?= $httpResponseCode ?>']}`;
    </script>
</body>